/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 97
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_module = 3,
  anon_sym_COLON = 4,
  aux_sym_module_signature_token1 = 5,
  sym_package_identifier = 6,
  sym_module_identifier = 7,
  anon_sym_experimental = 8,
  anon_sym_sol3 = 9,
  anon_sym_application = 10,
  anon_sym_let = 11,
  anon_sym_EQ = 12,
  anon_sym_expect = 13,
  anon_sym_otherwise = 14,
  anon_sym_EQ_EQ = 15,
  anon_sym_BANG_EQ = 16,
  anon_sym_LBRACE = 17,
  anon_sym_DASH_GT = 18,
  anon_sym_RBRACE = 19,
  sym_int_literal = 20,
  sym_decimal_literal = 21,
  sym_dont_care = 22,
  sym_ignore = 23,
  anon_sym_DQUOTE = 24,
  aux_sym_string_literal_token1 = 25,
  aux_sym_string_literal_token2 = 26,
  aux_sym_string_literal_token3 = 27,
  sym__multiline_string_literal = 28,
  sym_source_file = 29,
  sym_doc_string = 30,
  sym_script_decl = 31,
  sym_module_decl = 32,
  sym_experimental_module_decl = 33,
  sym_kernel_module_decl = 34,
  sym_application_decl = 35,
  sym_module_signature = 36,
  sym_experimental_module_signature = 37,
  sym_kernel_module_signature = 38,
  sym_application_signature = 39,
  sym__toplevel_decl = 40,
  sym_let_decl = 41,
  sym_expect_decl = 42,
  sym__complex_expression = 43,
  sym__expression = 44,
  sym_comparison_expression = 45,
  sym_function_expression = 46,
  sym_function_params = 47,
  sym__primitive_value = 48,
  sym_string_literal = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym_source_file_repeat2 = 51,
  aux_sym_script_decl_repeat1 = 52,
  aux_sym_module_decl_repeat1 = 53,
  aux_sym_function_params_repeat1 = 54,
  aux_sym_string_literal_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_module] = "module",
  [anon_sym_COLON] = ":",
  [aux_sym_module_signature_token1] = "module_identifier",
  [sym_package_identifier] = "package_identifier",
  [sym_module_identifier] = "module_identifier",
  [anon_sym_experimental] = "package_identifier",
  [anon_sym_sol3] = "package_identifier",
  [anon_sym_application] = "application",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_expect] = "expect",
  [anon_sym_otherwise] = "otherwise",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_RBRACE] = "}",
  [sym_int_literal] = "int_literal",
  [sym_decimal_literal] = "decimal_literal",
  [sym_dont_care] = "dont_care",
  [sym_ignore] = "ignore",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [aux_sym_string_literal_token3] = "string_literal_token3",
  [sym__multiline_string_literal] = "_multiline_string_literal",
  [sym_source_file] = "source_file",
  [sym_doc_string] = "doc_string",
  [sym_script_decl] = "script_decl",
  [sym_module_decl] = "module_decl",
  [sym_experimental_module_decl] = "experimental_module_decl",
  [sym_kernel_module_decl] = "kernel_module_decl",
  [sym_application_decl] = "application_decl",
  [sym_module_signature] = "module_signature",
  [sym_experimental_module_signature] = "experimental_module_signature",
  [sym_kernel_module_signature] = "kernel_module_signature",
  [sym_application_signature] = "application_signature",
  [sym__toplevel_decl] = "_toplevel_decl",
  [sym_let_decl] = "let_decl",
  [sym_expect_decl] = "expect_decl",
  [sym__complex_expression] = "_complex_expression",
  [sym__expression] = "_expression",
  [sym_comparison_expression] = "comparison_expression",
  [sym_function_expression] = "function_expression",
  [sym_function_params] = "function_params",
  [sym__primitive_value] = "_primitive_value",
  [sym_string_literal] = "string_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_script_decl_repeat1] = "script_decl_repeat1",
  [aux_sym_module_decl_repeat1] = "module_decl_repeat1",
  [aux_sym_function_params_repeat1] = "function_params_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_module_signature_token1] = sym_module_identifier,
  [sym_package_identifier] = sym_package_identifier,
  [sym_module_identifier] = sym_module_identifier,
  [anon_sym_experimental] = sym_package_identifier,
  [anon_sym_sol3] = sym_package_identifier,
  [anon_sym_application] = anon_sym_application,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_expect] = anon_sym_expect,
  [anon_sym_otherwise] = anon_sym_otherwise,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_int_literal] = sym_int_literal,
  [sym_decimal_literal] = sym_decimal_literal,
  [sym_dont_care] = sym_dont_care,
  [sym_ignore] = sym_ignore,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [aux_sym_string_literal_token3] = aux_sym_string_literal_token3,
  [sym__multiline_string_literal] = sym__multiline_string_literal,
  [sym_source_file] = sym_source_file,
  [sym_doc_string] = sym_doc_string,
  [sym_script_decl] = sym_script_decl,
  [sym_module_decl] = sym_module_decl,
  [sym_experimental_module_decl] = sym_experimental_module_decl,
  [sym_kernel_module_decl] = sym_kernel_module_decl,
  [sym_application_decl] = sym_application_decl,
  [sym_module_signature] = sym_module_signature,
  [sym_experimental_module_signature] = sym_experimental_module_signature,
  [sym_kernel_module_signature] = sym_kernel_module_signature,
  [sym_application_signature] = sym_application_signature,
  [sym__toplevel_decl] = sym__toplevel_decl,
  [sym_let_decl] = sym_let_decl,
  [sym_expect_decl] = sym_expect_decl,
  [sym__complex_expression] = sym__complex_expression,
  [sym__expression] = sym__expression,
  [sym_comparison_expression] = sym_comparison_expression,
  [sym_function_expression] = sym_function_expression,
  [sym_function_params] = sym_function_params,
  [sym__primitive_value] = sym__primitive_value,
  [sym_string_literal] = sym_string_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_script_decl_repeat1] = aux_sym_script_decl_repeat1,
  [aux_sym_module_decl_repeat1] = aux_sym_module_decl_repeat1,
  [aux_sym_function_params_repeat1] = aux_sym_function_params_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_module_signature_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_package_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_module_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_experimental] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_sol3] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_application] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_expect] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_otherwise] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_int_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_dont_care] = {
    .visible = true,
    .named = true,
  },
  [sym_ignore] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_token3] = {
    .visible = false,
    .named = false,
  },
  [sym__multiline_string_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_string] = {
    .visible = true,
    .named = true,
  },
  [sym_script_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_module_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_experimental_module_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_kernel_module_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_application_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_module_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_experimental_module_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_kernel_module_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_application_signature] = {
    .visible = true,
    .named = true,
  },
  [sym__toplevel_decl] = {
    .visible = false,
    .named = true,
  },
  [sym_let_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_expect_decl] = {
    .visible = true,
    .named = true,
  },
  [sym__complex_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_comparison_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_params] = {
    .visible = true,
    .named = true,
  },
  [sym__primitive_value] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_script_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_binding = 1,
  field_body = 2,
  field_condition = 3,
  field_docs = 4,
  field_implicit_return = 5,
  field_left = 6,
  field_params = 7,
  field_right = 8,
  field_signature = 9,
  field_value = 10,
  field_warning = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_binding] = "binding",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_docs] = "docs",
  [field_implicit_return] = "implicit_return",
  [field_left] = "left",
  [field_params] = "params",
  [field_right] = "right",
  [field_signature] = "signature",
  [field_value] = "value",
  [field_warning] = "warning",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_signature, 0},
  [1] =
    {field_condition, 1},
  [2] =
    {field_docs, 0},
    {field_signature, 1},
  [4] =
    {field_binding, 1},
    {field_value, 3},
  [6] =
    {field_left, 0},
    {field_right, 2},
  [8] =
    {field_condition, 1},
    {field_warning, 2},
    {field_warning, 3},
  [11] =
    {field_implicit_return, 3},
    {field_params, 1},
  [13] =
    {field_body, 3},
    {field_implicit_return, 4},
    {field_params, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 9,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 25,
  [32] = 32,
  [33] = 33,
  [34] = 27,
  [35] = 32,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 38,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 46,
  [49] = 36,
  [50] = 50,
  [51] = 45,
  [52] = 44,
  [53] = 33,
  [54] = 54,
  [55] = 55,
  [56] = 42,
  [57] = 57,
  [58] = 58,
  [59] = 43,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 63,
  [65] = 65,
  [66] = 66,
  [67] = 57,
  [68] = 68,
  [69] = 55,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 74,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 87,
  [92] = 78,
  [93] = 93,
  [94] = 86,
  [95] = 93,
  [96] = 90,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '!', 28,
        '"', 93,
        '#', 42,
        '-', 26,
        '0', 88,
        ':', 43,
        '=', 67,
        '\\', 1,
        '_', 91,
        'e', 86,
        's', 82,
        '{', 70,
        '}', 72,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(89);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '^') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(96);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '"') ADVANCE(93);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(94);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(93);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '0') ADVANCE(88);
      if (lookahead == '=') ADVANCE(66);
      if (lookahead == '{') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(89);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(32);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(33);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(33);
      if (lookahead == '}') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(33);
      if (lookahead == '}') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(33);
      if (lookahead == '}') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(33);
      if (lookahead == '}') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(33);
      if (lookahead == '}') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(33);
      if (lookahead == '}') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(33);
      if (lookahead == '}') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '"') ADVANCE(100);
      if (lookahead == '}') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == '"') ADVANCE(4);
      END_STATE();
    case 18:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(6);
      END_STATE();
    case 19:
      if (lookahead == '"') ADVANCE(16);
      if (lookahead == '}') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 20:
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == 'e') ADVANCE(57);
      if (lookahead == 's') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(59);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == 'e') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(59);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == '#') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      END_STATE();
    case 23:
      if (lookahead == '#') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 24:
      if (lookahead == '.') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      if (lookahead == '0') ADVANCE(24);
      if (lookahead == '>') ADVANCE(71);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 27:
      if (lookahead == '0') ADVANCE(24);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 28:
      if (lookahead == '=') ADVANCE(69);
      END_STATE();
    case 29:
      if (lookahead == '=') ADVANCE(68);
      END_STATE();
    case 30:
      if (lookahead == '>') ADVANCE(71);
      END_STATE();
    case 31:
      if (lookahead == '\\') ADVANCE(98);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(6);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(8);
      if (lookahead == '}') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(15);
      END_STATE();
    case 34:
      if (lookahead == '}') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(34);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 38:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 39:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '!', 28,
        '"', 93,
        '#', 42,
        '-', 26,
        '0', 88,
        '=', 67,
        '\\', 1,
        '_', 91,
        'e', 86,
        's', 82,
        '{', 70,
        '}', 72,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(89);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      if (lookahead == '!') ADVANCE(28);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '_') ADVANCE(91);
      if (lookahead == '}') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(40);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '3') ADVANCE(64);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 'a') ADVANCE(50);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 'e') ADVANCE(55);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 'e') ADVANCE(52);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(51);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 'l') ADVANCE(44);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 'l') ADVANCE(62);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 'm') ADVANCE(47);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 'n') ADVANCE(56);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 'o') ADVANCE(49);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 'p') ADVANCE(46);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 'r') ADVANCE(48);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 't') ADVANCE(45);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == 'x') ADVANCE(54);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_module_signature_token1);
      if (lookahead == '/') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_package_identifier);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_module_identifier);
      if (lookahead == '/') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_experimental);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_experimental);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_sol3);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_sol3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(68);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '3') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '.') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '.') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_decimal_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_dont_care);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_ignore);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(94);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(96);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_string_literal_token3);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym__multiline_string_literal);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym__multiline_string_literal);
      if (lookahead == '}') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(34);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(3);
      if (lookahead == 'm') ADVANCE(4);
      if (lookahead == 'o') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'p') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'x') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'p') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'p') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 'w') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_expect);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 32:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_otherwise);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_application);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 40},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 40},
  [7] = {.lex_state = 40},
  [8] = {.lex_state = 40},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 40},
  [11] = {.lex_state = 40},
  [12] = {.lex_state = 40},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 40},
  [16] = {.lex_state = 40},
  [17] = {.lex_state = 40},
  [18] = {.lex_state = 40},
  [19] = {.lex_state = 40},
  [20] = {.lex_state = 40},
  [21] = {.lex_state = 40},
  [22] = {.lex_state = 40},
  [23] = {.lex_state = 40},
  [24] = {.lex_state = 40},
  [25] = {.lex_state = 40},
  [26] = {.lex_state = 40},
  [27] = {.lex_state = 40},
  [28] = {.lex_state = 40},
  [29] = {.lex_state = 40},
  [30] = {.lex_state = 40},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 40},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 40},
  [40] = {.lex_state = 40},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 40},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 40},
  [50] = {.lex_state = 40},
  [51] = {.lex_state = 40},
  [52] = {.lex_state = 40},
  [53] = {.lex_state = 40},
  [54] = {.lex_state = 40},
  [55] = {.lex_state = 40},
  [56] = {.lex_state = 40},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 40},
  [60] = {.lex_state = 40},
  [61] = {.lex_state = 40},
  [62] = {.lex_state = 40},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 40},
  [66] = {.lex_state = 40},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 40},
  [69] = {.lex_state = 40},
  [70] = {.lex_state = 20},
  [71] = {.lex_state = 40},
  [72] = {.lex_state = 40},
  [73] = {.lex_state = 21},
  [74] = {.lex_state = 40},
  [75] = {.lex_state = 40},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 40},
  [79] = {.lex_state = 23},
  [80] = {.lex_state = 23},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 20},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 23},
  [89] = {.lex_state = 23},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 40},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_experimental] = ACTIONS(1),
    [anon_sym_sol3] = ACTIONS(1),
    [anon_sym_application] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_expect] = ACTIONS(1),
    [anon_sym_otherwise] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_int_literal] = ACTIONS(1),
    [sym_decimal_literal] = ACTIONS(1),
    [sym_dont_care] = ACTIONS(1),
    [sym_ignore] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_literal_token2] = ACTIONS(1),
    [aux_sym_string_literal_token3] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(76),
    [sym_doc_string] = STATE(18),
    [sym_script_decl] = STATE(77),
    [sym_module_decl] = STATE(77),
    [sym_experimental_module_decl] = STATE(11),
    [sym_kernel_module_decl] = STATE(7),
    [sym_application_decl] = STATE(77),
    [sym_module_signature] = STATE(17),
    [sym_experimental_module_signature] = STATE(16),
    [sym_kernel_module_signature] = STATE(15),
    [sym__toplevel_decl] = STATE(40),
    [sym_let_decl] = STATE(40),
    [sym_expect_decl] = STATE(40),
    [aux_sym_script_decl_repeat1] = STATE(40),
    [aux_sym_module_decl_repeat1] = STATE(18),
    [sym_comment] = ACTIONS(3),
    [anon_sym_module] = ACTIONS(5),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_expect] = ACTIONS(9),
    [sym__multiline_string_literal] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_expect,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 3,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
    STATE(9), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
    STATE(91), 5,
      sym__complex_expression,
      sym__expression,
      sym_function_expression,
      sym__primitive_value,
      sym_string_literal,
  [34] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_expect,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 3,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
    STATE(9), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
    STATE(87), 5,
      sym__complex_expression,
      sym__expression,
      sym_function_expression,
      sym__primitive_value,
      sym_string_literal,
  [68] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_expect,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 3,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
    STATE(3), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
    STATE(96), 5,
      sym__complex_expression,
      sym__expression,
      sym_function_expression,
      sym__primitive_value,
      sym_string_literal,
  [102] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_expect,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 3,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
    STATE(2), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
    STATE(90), 5,
      sym__complex_expression,
      sym__expression,
      sym_function_expression,
      sym__primitive_value,
      sym_string_literal,
  [136] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_module,
    ACTIONS(11), 1,
      sym__multiline_string_literal,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      sym_kernel_module_signature,
    STATE(16), 1,
      sym_experimental_module_signature,
    STATE(17), 1,
      sym_module_signature,
    STATE(39), 2,
      sym_doc_string,
      aux_sym_module_decl_repeat1,
    STATE(8), 4,
      sym_module_decl,
      sym_experimental_module_decl,
      sym_kernel_module_decl,
      aux_sym_source_file_repeat2,
  [168] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_module,
    ACTIONS(11), 1,
      sym__multiline_string_literal,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      sym_kernel_module_signature,
    STATE(16), 1,
      sym_experimental_module_signature,
    STATE(17), 1,
      sym_module_signature,
    STATE(39), 2,
      sym_doc_string,
      aux_sym_module_decl_repeat1,
    STATE(6), 4,
      sym_module_decl,
      sym_experimental_module_decl,
      sym_kernel_module_decl,
      aux_sym_source_file_repeat2,
  [200] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_module,
    ACTIONS(38), 1,
      sym__multiline_string_literal,
    STATE(15), 1,
      sym_kernel_module_signature,
    STATE(16), 1,
      sym_experimental_module_signature,
    STATE(17), 1,
      sym_module_signature,
    STATE(39), 2,
      sym_doc_string,
      aux_sym_module_decl_repeat1,
    STATE(8), 4,
      sym_module_decl,
      sym_experimental_module_decl,
      sym_kernel_module_decl,
      aux_sym_source_file_repeat2,
  [232] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_let,
    ACTIONS(46), 1,
      anon_sym_expect,
    ACTIONS(49), 2,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(41), 3,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
    STATE(9), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [257] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__multiline_string_literal,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_module,
    STATE(16), 1,
      sym_experimental_module_signature,
    STATE(17), 1,
      sym_module_signature,
    STATE(50), 2,
      sym_doc_string,
      aux_sym_module_decl_repeat1,
    STATE(12), 3,
      sym_module_decl,
      sym_experimental_module_decl,
      aux_sym_source_file_repeat1,
  [285] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__multiline_string_literal,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_module,
    STATE(16), 1,
      sym_experimental_module_signature,
    STATE(17), 1,
      sym_module_signature,
    STATE(50), 2,
      sym_doc_string,
      aux_sym_module_decl_repeat1,
    STATE(10), 3,
      sym_module_decl,
      sym_experimental_module_decl,
      aux_sym_source_file_repeat1,
  [313] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      anon_sym_module,
    ACTIONS(58), 1,
      sym__multiline_string_literal,
    STATE(16), 1,
      sym_experimental_module_signature,
    STATE(17), 1,
      sym_module_signature,
    STATE(50), 2,
      sym_doc_string,
      aux_sym_module_decl_repeat1,
    STATE(12), 3,
      sym_module_decl,
      sym_experimental_module_decl,
      aux_sym_source_file_repeat1,
  [341] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(63), 2,
      sym_int_literal,
      sym_decimal_literal,
    STATE(56), 5,
      sym__complex_expression,
      sym__expression,
      sym_function_expression,
      sym__primitive_value,
      sym_string_literal,
  [365] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_LBRACE,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 2,
      sym_int_literal,
      sym_decimal_literal,
    STATE(42), 5,
      sym__complex_expression,
      sym__expression,
      sym_function_expression,
      sym__primitive_value,
      sym_string_literal,
  [389] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(21), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [410] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(20), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [431] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(77), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(19), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [452] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_module,
    ACTIONS(11), 1,
      sym__multiline_string_literal,
    ACTIONS(79), 1,
      anon_sym_application,
    STATE(23), 1,
      sym_module_signature,
    STATE(24), 1,
      sym_experimental_module_signature,
    STATE(30), 1,
      sym_kernel_module_signature,
    STATE(37), 1,
      sym_application_signature,
    STATE(62), 2,
      sym_doc_string,
      aux_sym_module_decl_repeat1,
  [481] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(22), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [502] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(83), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(22), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [523] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(22), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [544] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_let,
    ACTIONS(90), 1,
      anon_sym_expect,
    ACTIONS(49), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(22), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [565] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(29), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [586] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(95), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(28), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [607] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_let,
      anon_sym_expect,
      anon_sym_otherwise,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
      sym__multiline_string_literal,
  [622] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(22), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [643] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 9,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_let,
      anon_sym_expect,
      anon_sym_otherwise,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACE,
      sym__multiline_string_literal,
  [658] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(103), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(22), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [679] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(105), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(22), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [700] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(107), 3,
      ts_builtin_sym_end,
      anon_sym_module,
      sym__multiline_string_literal,
    STATE(26), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [721] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(109), 6,
      anon_sym_let,
      anon_sym_expect,
      anon_sym_otherwise,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
  [737] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(111), 1,
      sym_identifier,
    STATE(53), 1,
      sym_comparison_expression,
    ACTIONS(113), 2,
      sym_int_literal,
      sym_decimal_literal,
    STATE(74), 3,
      sym__expression,
      sym__primitive_value,
      sym_string_literal,
  [759] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_otherwise,
    ACTIONS(119), 2,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(115), 5,
      anon_sym_let,
      anon_sym_expect,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
  [777] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(121), 6,
      anon_sym_let,
      anon_sym_expect,
      anon_sym_otherwise,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
  [793] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      sym_identifier,
    STATE(33), 1,
      sym_comparison_expression,
    ACTIONS(125), 2,
      sym_int_literal,
      sym_decimal_literal,
    STATE(75), 3,
      sym__expression,
      sym__primitive_value,
      sym_string_literal,
  [815] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 2,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(127), 6,
      anon_sym_let,
      anon_sym_expect,
      anon_sym_otherwise,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
  [831] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    STATE(47), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [850] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(135), 2,
      sym_int_literal,
      sym_decimal_literal,
    STATE(59), 3,
      sym__expression,
      sym__primitive_value,
      sym_string_literal,
  [869] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_module,
    ACTIONS(11), 1,
      sym__multiline_string_literal,
    STATE(23), 1,
      sym_module_signature,
    STATE(24), 1,
      sym_experimental_module_signature,
    STATE(30), 1,
      sym_kernel_module_signature,
    STATE(62), 2,
      sym_doc_string,
      aux_sym_module_decl_repeat1,
  [892] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    STATE(22), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [911] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 2,
      sym_int_literal,
      sym_decimal_literal,
    STATE(43), 3,
      sym__expression,
      sym__primitive_value,
      sym_string_literal,
  [930] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 2,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(143), 5,
      anon_sym_let,
      anon_sym_expect,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
  [945] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(147), 5,
      anon_sym_let,
      anon_sym_expect,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
  [960] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 2,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(151), 5,
      anon_sym_let,
      anon_sym_expect,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
  [975] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 2,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
    ACTIONS(155), 5,
      anon_sym_let,
      anon_sym_expect,
      sym_identifier,
      sym_int_literal,
      sym_decimal_literal,
  [990] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    ACTIONS(159), 1,
      sym_identifier,
    ACTIONS(161), 2,
      sym_int_literal,
      sym_decimal_literal,
    STATE(36), 3,
      sym__expression,
      sym__primitive_value,
      sym_string_literal,
  [1009] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_expect,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
    STATE(22), 4,
      sym__toplevel_decl,
      sym_let_decl,
      sym_expect_decl,
      aux_sym_script_decl_repeat1,
  [1028] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(167), 2,
      sym_int_literal,
      sym_decimal_literal,
    STATE(49), 3,
      sym__expression,
      sym__primitive_value,
      sym_string_literal,
  [1047] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_let,
      anon_sym_expect,
      anon_sym_otherwise,
      sym__multiline_string_literal,
  [1059] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__multiline_string_literal,
    ACTIONS(51), 1,
      anon_sym_module,
    STATE(23), 1,
      sym_module_signature,
    STATE(24), 1,
      sym_experimental_module_signature,
    STATE(62), 2,
      sym_doc_string,
      aux_sym_module_decl_repeat1,
  [1079] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 6,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_let,
      anon_sym_expect,
      anon_sym_RBRACE,
      sym__multiline_string_literal,
  [1091] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 6,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_let,
      anon_sym_expect,
      anon_sym_RBRACE,
      sym__multiline_string_literal,
  [1103] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_otherwise,
    ACTIONS(119), 5,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_let,
      anon_sym_expect,
      sym__multiline_string_literal,
  [1117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 5,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_let,
      anon_sym_expect,
      sym__multiline_string_literal,
  [1128] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym_dont_care,
    STATE(60), 1,
      aux_sym_function_params_repeat1,
    STATE(93), 1,
      sym_function_params,
    ACTIONS(173), 2,
      sym_identifier,
      sym_ignore,
  [1145] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 5,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_let,
      anon_sym_expect,
      sym__multiline_string_literal,
  [1156] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(181), 3,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
      aux_sym_string_literal_token3,
  [1171] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(185), 3,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
      aux_sym_string_literal_token3,
  [1186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 5,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_let,
      anon_sym_expect,
      sym__multiline_string_literal,
  [1197] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_DASH_GT,
    ACTIONS(192), 1,
      sym_dont_care,
    STATE(61), 1,
      aux_sym_function_params_repeat1,
    ACTIONS(188), 2,
      sym_identifier,
      sym_ignore,
  [1214] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_DASH_GT,
    ACTIONS(199), 1,
      sym_dont_care,
    STATE(61), 1,
      aux_sym_function_params_repeat1,
    ACTIONS(194), 2,
      sym_identifier,
      sym_ignore,
  [1231] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym__multiline_string_literal,
    ACTIONS(202), 2,
      anon_sym_module,
      anon_sym_application,
    STATE(62), 2,
      sym_doc_string,
      aux_sym_module_decl_repeat1,
  [1246] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(209), 3,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
      aux_sym_string_literal_token3,
  [1261] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(209), 3,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
      aux_sym_string_literal_token3,
  [1276] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 5,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_let,
      anon_sym_expect,
      sym__multiline_string_literal,
  [1287] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 5,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_let,
      anon_sym_expect,
      sym__multiline_string_literal,
  [1298] = 4,
    ACTIONS(177), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_DQUOTE,
    STATE(63), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(219), 3,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
      aux_sym_string_literal_token3,
  [1313] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 5,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_let,
      anon_sym_expect,
      sym__multiline_string_literal,
  [1324] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym_dont_care,
    STATE(60), 1,
      aux_sym_function_params_repeat1,
    STATE(95), 1,
      sym_function_params,
    ACTIONS(173), 2,
      sym_identifier,
      sym_ignore,
  [1341] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      aux_sym_module_signature_token1,
    ACTIONS(225), 1,
      sym_package_identifier,
    ACTIONS(227), 1,
      anon_sym_experimental,
    ACTIONS(229), 1,
      anon_sym_sol3,
  [1357] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 3,
      anon_sym_module,
      anon_sym_application,
      sym__multiline_string_literal,
  [1366] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 3,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_expect,
  [1375] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      aux_sym_module_signature_token1,
    ACTIONS(225), 1,
      sym_package_identifier,
    ACTIONS(227), 1,
      anon_sym_experimental,
  [1388] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1396] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1404] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
  [1411] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
  [1418] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identifier,
  [1425] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_module_identifier,
  [1432] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_module_identifier,
  [1439] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_COLON,
  [1446] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_COLON,
  [1453] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_COLON,
  [1460] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_COLON,
  [1467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_package_identifier,
  [1474] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_EQ,
  [1481] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
  [1488] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym_module_identifier,
  [1495] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      sym_module_identifier,
  [1502] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_RBRACE,
  [1509] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_RBRACE,
  [1516] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym_identifier,
  [1523] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_DASH_GT,
  [1530] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_EQ,
  [1537] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_DASH_GT,
  [1544] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 102,
  [SMALL_STATE(6)] = 136,
  [SMALL_STATE(7)] = 168,
  [SMALL_STATE(8)] = 200,
  [SMALL_STATE(9)] = 232,
  [SMALL_STATE(10)] = 257,
  [SMALL_STATE(11)] = 285,
  [SMALL_STATE(12)] = 313,
  [SMALL_STATE(13)] = 341,
  [SMALL_STATE(14)] = 365,
  [SMALL_STATE(15)] = 389,
  [SMALL_STATE(16)] = 410,
  [SMALL_STATE(17)] = 431,
  [SMALL_STATE(18)] = 452,
  [SMALL_STATE(19)] = 481,
  [SMALL_STATE(20)] = 502,
  [SMALL_STATE(21)] = 523,
  [SMALL_STATE(22)] = 544,
  [SMALL_STATE(23)] = 565,
  [SMALL_STATE(24)] = 586,
  [SMALL_STATE(25)] = 607,
  [SMALL_STATE(26)] = 622,
  [SMALL_STATE(27)] = 643,
  [SMALL_STATE(28)] = 658,
  [SMALL_STATE(29)] = 679,
  [SMALL_STATE(30)] = 700,
  [SMALL_STATE(31)] = 721,
  [SMALL_STATE(32)] = 737,
  [SMALL_STATE(33)] = 759,
  [SMALL_STATE(34)] = 777,
  [SMALL_STATE(35)] = 793,
  [SMALL_STATE(36)] = 815,
  [SMALL_STATE(37)] = 831,
  [SMALL_STATE(38)] = 850,
  [SMALL_STATE(39)] = 869,
  [SMALL_STATE(40)] = 892,
  [SMALL_STATE(41)] = 911,
  [SMALL_STATE(42)] = 930,
  [SMALL_STATE(43)] = 945,
  [SMALL_STATE(44)] = 960,
  [SMALL_STATE(45)] = 975,
  [SMALL_STATE(46)] = 990,
  [SMALL_STATE(47)] = 1009,
  [SMALL_STATE(48)] = 1028,
  [SMALL_STATE(49)] = 1047,
  [SMALL_STATE(50)] = 1059,
  [SMALL_STATE(51)] = 1079,
  [SMALL_STATE(52)] = 1091,
  [SMALL_STATE(53)] = 1103,
  [SMALL_STATE(54)] = 1117,
  [SMALL_STATE(55)] = 1128,
  [SMALL_STATE(56)] = 1145,
  [SMALL_STATE(57)] = 1156,
  [SMALL_STATE(58)] = 1171,
  [SMALL_STATE(59)] = 1186,
  [SMALL_STATE(60)] = 1197,
  [SMALL_STATE(61)] = 1214,
  [SMALL_STATE(62)] = 1231,
  [SMALL_STATE(63)] = 1246,
  [SMALL_STATE(64)] = 1261,
  [SMALL_STATE(65)] = 1276,
  [SMALL_STATE(66)] = 1287,
  [SMALL_STATE(67)] = 1298,
  [SMALL_STATE(68)] = 1313,
  [SMALL_STATE(69)] = 1324,
  [SMALL_STATE(70)] = 1341,
  [SMALL_STATE(71)] = 1357,
  [SMALL_STATE(72)] = 1366,
  [SMALL_STATE(73)] = 1375,
  [SMALL_STATE(74)] = 1388,
  [SMALL_STATE(75)] = 1396,
  [SMALL_STATE(76)] = 1404,
  [SMALL_STATE(77)] = 1411,
  [SMALL_STATE(78)] = 1418,
  [SMALL_STATE(79)] = 1425,
  [SMALL_STATE(80)] = 1432,
  [SMALL_STATE(81)] = 1439,
  [SMALL_STATE(82)] = 1446,
  [SMALL_STATE(83)] = 1453,
  [SMALL_STATE(84)] = 1460,
  [SMALL_STATE(85)] = 1467,
  [SMALL_STATE(86)] = 1474,
  [SMALL_STATE(87)] = 1481,
  [SMALL_STATE(88)] = 1488,
  [SMALL_STATE(89)] = 1495,
  [SMALL_STATE(90)] = 1502,
  [SMALL_STATE(91)] = 1509,
  [SMALL_STATE(92)] = 1516,
  [SMALL_STATE(93)] = 1523,
  [SMALL_STATE(94)] = 1530,
  [SMALL_STATE(95)] = 1537,
  [SMALL_STATE(96)] = 1544,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(70),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(71),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_script_decl_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_script_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_script_decl_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kernel_module_decl, 1, 0, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_experimental_module_decl, 1, 0, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_decl, 1, 0, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_decl, 2, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_experimental_module_decl, 2, 0, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kernel_module_decl, 2, 0, 1),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_script_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_script_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_decl, 2, 0, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_experimental_module_decl, 2, 0, 3),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kernel_module_decl, 3, 0, 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_experimental_module_decl, 3, 0, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_decl, 3, 0, 3),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kernel_module_decl, 2, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expect_decl, 2, 0, 2),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expect_decl, 2, 0, 2),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison_expression, 3, 0, 5),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_expression, 3, 0, 5),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application_decl, 2, 0, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_decl, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_decl, 4, 0, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_decl, 4, 0, 4),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expect_decl, 4, 0, 6),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expect_decl, 4, 0, 6),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_expression, 5, 0, 7),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_expression, 5, 0, 7),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_expression, 6, 0, 8),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_expression, 6, 0, 8),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application_decl, 3, 0, 3),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_kernel_module_signature, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_params, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_params_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_params_repeat1, 2, 0, 0),
  [199] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_params_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_decl_repeat1, 2, 0, 0),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_signature, 4, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_signature, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_experimental_module_signature, 4, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doc_string, 1, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application_signature, 4, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [239] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sol3(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sol3",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
