[package]
name = "lsp"
version = "0.0.1"
edition = "2024"
workspace = "../cli"

[dependencies]
tokio = { version = "1.44", features = ["full"] }
tower-lsp = { version = "0.20", features = ["proposed"] }
