pub const INITIAL_CODEGEN_BUFFER_LINE_LENGTH = 4096;
pub const INITIAL_EXPORT_LIST_SIZE = 32;
pub const INITIAL_NURSERY_SIZE = 512;
pub const INITIAL_VISITOR_LIST_SIZE = 8;
pub const MAX_FILE_SIZE_BYTES = 4096;
pub const MAX_PARSER_ARTIFACT_SIZE_BYTES: comptime_int = 16 * 1024 * 1024;
