[package]
name = "canapea-cli-scripting"
version = "0.0.1"
authors = ["Martin Feineis <mfeineis@users.noreply.github.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.2.20"
