name: parser

env:
  CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/parser**
      - parser/**
  pull_request:
    paths:
      - .github/workflows/parser**
      - parser/**

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test-bindings:
    name: Test bindings
    # # FIXME:
    # # Setting the working-directory only works on our "own" run entries
    # # not on external actions, which is rather stupid for multi-project
    # # setups... so, let's copy stuff like in the olden days... :-/
    # defaults:
    #   run:
    #     working-directory: ./parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-14, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'parser'
          sparse-checkout-cone-mode: false
      - name: Copy parser into working dir
        # TODO: rm on Windows does not support -rf, do sth better
        # rm -rf parser/
        run: |-
          mv parser/* .
      - name: Configure NPM for CI usage
        # cp ci/npmrc "${HOME}/.npmrc"
        run: |-
          npm config list
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.6
      - name: Check CI environment setup
        run: |-
          ci/00-ensure-test-env.sh
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: true
          test-parser: true
          test-rust: true
          test-node: true
          test-python: true
          test-go: true
          test-swift: true
      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          files: |
            examples/**/*.cnp
          #invalid-files: |
          #  examples/cpython/Lib/test/tokenizedata/badsyntax_3131.py
      - name: Get rid of all local changes
        run: |-
          git restore . || true
          git clean -f || true

  # test-node:
  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest] #, macos-14 , windows-latest]
  #       node-version: [20, 22]

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         #python-version: "3.12"
  #         python-version: "3"
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: npm install
  #       run: |
  #         npm i
  #     - name: Unit tests
  #       run: |
  #         npm test
  #     - name: Test examples
  #       run: |
  #         script/parse-examples
  #       shell: bash
