name: ci-parser

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/parser*
      - parser/ci/**
      - parser/tree-sitter.json
      - parser/package.json
      - parser/grammar.js
      - parser/src/**
      - parser/test/**
      - parser/examples/**
      - parser/bindings/**
      - parser/binding.gyp
  pull_request:
    paths:
      - .github/workflows/parser*
      - parser/ci/**
      - parser/tree-sitter.json
      - parser/package.json
      - parser/grammar.js
      - parser/src/**
      - parser/test/**
      - parser/examples/**
      - parser/bindings/**
      - parser/binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    defaults:
      run:
        working-directory: ./parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Check CI environment setup
        run: |-
          ci/00-ensure-test-env.sh
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          working-directory: ./parser
          generate: true
          test-parser: true
          test-rust: true
          test-node: true
          test-python: true
          test-go: true
          test-swift: true
      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          working-directory: ./parser
          files: |
            examples/**/*.lang0
          #invalid-files: |
          #  examples/cpython/Lib/test/tokenizedata/badsyntax_3131.py