name: ci-parser

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/parser*
      - parser/ci/**
      - parser/tree-sitter.json
      - parser/package.json
      - parser/grammar.js
      - parser/src/**
      - parser/test/**
      - parser/examples/**
      - parser/bindings/**
      - parser/binding.gyp
  pull_request:
    paths:
      - .github/workflows/parser*
      - parser/ci/**
      - parser/tree-sitter.json
      - parser/package.json
      - parser/grammar.js
      - parser/src/**
      - parser/test/**
      - parser/examples/**
      - parser/bindings/**
      - parser/binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    # # FIXME:
    # # Setting the working-directory only works on our "own" run entries
    # # not on external actions, which is rather stupid for multi-project
    # # setups... so, let's copy stuff like in the olden days... :-/
    # defaults:
    #   run:
    #     working-directory: ./parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-14] #, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'parser'
          sparse-checkout-cone-mode: false
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Copy parser into working dir
        #  ls -lah
        #  ls -lah
        run: |-
          mv parser/* .
          rm -rf parser/
      - name: Check CI environment setup
        run: |-
          ci/00-ensure-test-env.sh
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: true
          test-parser: true
          test-rust: true
          test-node: false 
          # TODO: Set up our own test workflow for node
          #test-node: true
          test-python: true
          test-go: true
          test-swift: false
          # TODO: Set up our own test workflow for swift?
      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          files: |
            examples/**/*.lang0
          #invalid-files: |
          #  examples/cpython/Lib/test/tokenizedata/badsyntax_3131.py
      - name: Get rid of all local changes
        run: |-
          git restore . || true
          git clean || true
