name: vsext

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/vsext*
      - language-support-vscode/**
  pull_request:
    paths:
      - .github/workflows/vsext*
      - language-support-vscode/**

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    name: Build extension
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest] #, macos-14 , windows-latest]
        node-version: [22] # [20, 22]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and test
        run: |
          npm ci
          npm test
        env:
          CI: true